# .github/workflows/ci.yml
# Local CI pipeline for Go project
name: Go CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod tidy
      - name: Lint
        run: |
          go fmt ./...
          go vet ./...
      - name: Run tests
        run: go test -v ./...
      - name: Check documentation
        run: |
          test -f README.md && echo "README.md exists" || (echo "Missing README.md" && exit 1)
